name: C++ CI

on:
  push:
    branches:
      - main
      - stable/[0-9]+\.[0-9]+
      - hotfix/23\.2

jobs:
  start-vm:
    name: Start VM
    runs-on: trampoline
    outputs:
      label: ${{ steps.start-yc-runner.outputs.label }}
      instance-id: ${{ steps.start-yc-runner.outputs.instance-id }}
    steps:
      - name: Start YC runner
        id: start-yc-runner
        uses: yc-actions/yc-github-runner@v1
        with:
          mode: start
          yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}
          github-token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          folder-id: ${{ vars.YC_FOLDER_ID }}
          image-id: ${{ vars.YC_DEFAULT_IMAGE_ID }}
          zone-id: ${{ vars.YC_ZONE_ID }}
          subnet-id: ${{ vars.YC_SUBNET_ID }}
          cores: 16
          memory: 32GB
          core-fraction: 100
          disk-type: network-ssd-nonreplicated
          disk-size: 279GB

  checkout:
    name: Checkout sources
    needs: start-vm
    runs-on: ${{ needs.start-vm.outputs.label }}
    steps:
      - name: Checkout ytsaurus
        uses: actions/checkout@v3
        with:
          path: ytsaurus

      - name: Checkout ydb
        uses: actions/checkout@v3
        with:
          repository: ydb-platform/ydb
          ref: cc871496ef02852bf6ca96470fa61c253940ddf4
          path: ydb

  build:
    name: Build
    needs:
      - start-vm
      - checkout
    with:
      runs-on-value: ${{ needs.start-vm.outputs.label }}
      build-strawberry: true
      build-ytsaurus: true
      build-query-tracker: ${{ github.ref_name == 'main' || contains(github.ref_name, 'test') }}
      build-chyt: ${{ github.ref_name == 'main' || contains(github.ref_name, 'test') }}
      build-python: true
    uses: ./.github/workflows/build-jobs.yaml

  tag:
    name: Calculate docker tag
    needs:
      - start-vm
      - build
    runs-on: ${{ needs.start-vm.outputs.label }}
    outputs:
      image-tag: ${{ steps.tag.outputs.IMAGE_TAG }}
    steps:
      - name: Calculate docker tag
        id: tag
        run: |
          if [[ $GITHUB_REF =~ main$ ]];
          then
            IMAGE_TAG=dev
          elif [[ $GITHUB_REF =~ test ]];
          then
            IMAGE_TAG=test
          elif [[ $GITHUB_REF =~ stable ]];
          then
            IMAGE_TAG=dev-${GITHUB_REF#refs/*/stable/}
          elif [[ $GITHUB_REF =~ hotfix ]];
          then
            IMAGE_TAG=hotfix-${GITHUB_REF#refs/*/hotfix/}
          else
            IMAGE_TAG=dev-test
          fi
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_OUTPUT

  docker:
    name: Docker images
    needs:
      - start-vm
      - tag
    with:
      runs-on-value: ${{ needs.start-vm.outputs.label }}
      publish-ytsaurus: true
      publish-query-tracker: ${{ github.ref_name == 'main' || contains(github.ref_name, 'test') }}
      publish-chyt: ${{ github.ref_name == 'main' || contains(github.ref_name, 'test') }}
      publish-local: true
      publish-strawberry: ${{ github.ref_name == 'main' || contains(github.ref_name, 'test') }}
      image-tag: ${{ needs.tag.outputs.image-tag }}
    secrets:
      DOCKER_HUB_LOGIN: ${{ secrets.DOCKER_HUB_LOGIN }}
      DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
    uses: ./.github/workflows/docker-jobs.yaml

  check:
    name: Check
    needs:
      - start-vm
      - docker
    with:
      runs-on-value: ${{ needs.start-vm.outputs.label }}
    secrets:
      NEBIUS_TESTMO_TOKEN: ${{ secrets.NEBIUS_TESTMO_TOKEN }}
    uses: ./.github/workflows/check-jobs.yaml

  systest:
    name: systest
    if: github.ref_name == 'main'
    needs:
      - start-vm
      - tag
      - check
    runs-on: ${{ needs.start-vm.outputs.label }}
    steps:
      - name: Mark latest nightly
        run: |
          if [[ ${{ needs.tag.outputs.image-tag }} == 'dev' ]]
          then
            docker tag ytsaurus/ytsaurus-nightly:dev-${GITHUB_SHA} ytsaurus/ytsaurus-nightly:latest
            docker push ytsaurus/ytsaurus-nightly:latest
          fi

      - name: Download benchmarks
        uses: robinraju/release-downloader@v1.8
        with:
          latest: true
          fileName: "benchmark-0.0.1.tgz"

      - name: Docker systest
        shell: bash
        run: |
          mkdir -p ../docker-systest-build
          bash ./ytsaurus/yt/docker/systest/build.sh --ytsaurus-source-path $(pwd)/ytsaurus  --ytsaurus-build-path ../build --benchmarks-path benchmark-0.0.1.tgz --output-path ../docker-systest-build --image-tag latest
          docker push ytsaurus/ytsaurus-systest:latest

  stop-vm:
    name: Stop VM
    needs:
      - start-vm
      - systest
    runs-on: trampoline
    if: ${{ always() }}
    steps:
      - name: Stop YC runner
        uses: yc-actions/yc-github-runner@v1
        with:
          mode: stop
          yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}
          github-token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          label: ${{ needs.start-vm.outputs.label }}
          instance-id: ${{ needs.start-vm.outputs.instance-id }}

  send-notifications:
    name: Send notifications
    needs:
      - stop-vm
    runs-on: trampoline
    if: ${{ failure() }}
    steps:
      - name: Send telegram message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          disable_web_page_preview: true
          format: markdown
          message: |
            Workflow *${{github.workflow}}* failed: ${{github.server_url}}/${{github.repository}}/actions/runs/${{github.run_id}}.
            Git ${{github.ref_type}}: *${{github.ref_name}}*.
            Commit:
            ```
            ${{github.event.head_commit.message}}
            ```

